version: "3.8"
services:
  client:
    stdin_open: true
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile.client.prod
    ports:
      - "3000:80"
