version: "3.8"
services:
  client:
    stdin_open: true
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    image: ${APP_NAME}-client:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile.client.prod
